[tool.black]
line-length = 119
py36 = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | migrations
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''